name: CI

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Check links
      run: |
        pip3 install -r requirements.txt
        python3 check.py
    - name: Commit links
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -am "Update data"
        git push "https://bayotop:${{ secrets.PAT }}@github.com/bayotop/za-mamou-data.git" HEAD:master --follow-tags
