name: CI

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Check links
      run: |
        pip3 install -r requirements.txt
        python3 check.py
    - name: Commit links
      run: |
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git remote add publisher "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git checkout master
        git add -A
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp} ${GITHUB_SHA}" || exit 0
        git pull --rebase publisher master
        git push publisher master
