name: CI

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: fetch-links
      run: |
        pip install -r requirements.txt
        python check.py
    - name: commit-links
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -am "Update data"
        git push "https://bayotop:${{ secrets.PAT }}@github.com/bayotop/za-mamou-data.git" HEAD:master --follow-tags
