name: CI

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
    - name: fetch-links
      run: |
        python check.py
    - name: commit-links
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -am "Update data"
        git push "https://bayotop:${{ secrets.GITHUB_PERSONAL_TOKEN }}@github.com/bayotop/za-mamou-data.git" HEAD:master --follow-tags
